apiVersion: v2
appVersion: "2.7.1"
description: >
  Helm chart to deploy Open5gs UPF service on Kubernetes.
sources:
- http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs-logo.png
name: open5gs-upf
version: 2.2.3
annotations:
  artifacthub.io/category: networking
keywords:
- network
- ngc
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
